# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b59bb48fab1daa198e08fceffd3165c038392c125f7c0111624fad17b98f154a6e693ec251b911516d50d42a5257b47fea119e569a02c845748f2e254c1fd191

test:
  secret_key_base: 840f16814ca8cab4b184b2aef5dcccb4759f4cb342089d9c797f2cc3005698a741cb69a9d41e143f24741fd5fb019cb3219e31fcb24e16a1b42d347d4c403ba4

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
